# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_card_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.TextField(default='', max_length=255),
        ),
    ]
